[project]
name = "get-anime"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "aiohttp>=3.13.2",
    "attrs~=25.4.0",
    "beautifulsoup4~=4.14.3",
    "greenlet~=3.2.4",
    "httpx~=0.28.1",
    "jinja2~=3.1.6",
    "pillow>=12.0.0",
    "pydantic~=2.12.5",
    "pyinstaller~=6.17.0",
    "pyqt5==5.15.11",
    "pyqtwebengine==5.15.7",
    "pytest~=9.0.2",
    "pytest-mock~=3.15.1",
    "pytest-qt~=4.5.0",
    "python-dotenv~=1.2.2",
    "python-mpv~=1.0.8",
    "python-vlc~=3.0.21203",
    "qrcode~=8.2",
    "requests>=2.32.3",
    "sqlalchemy~=2.0.44",
    "typing-extensions~=4.15.0",
]
[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "pytest-qt>=4.5.0",
    "attrs>=25.4.0",
    "typing_extensions>=4.15.0",
    "SQLAlchemy>=2.0.44",
    "greenlet>=3.2.4",
    "jinja2>=3.1.6",
    "PyQt5==5.15.11",
    "PyQtWebEngine==5.15.7",
    "Pillow>=12.0.0",
    "pyinstaller>=6.17.0",
    "pydantic>=2.12.5",
    "requests>=2.32.3",
    "aiohttp>=3.13.2",
    "httpx>=0.28.1",
    "beautifulsoup4>=4.14.3",
    "python-vlc>=3.0.21203",
    "python-mpv>=1.0.8",
]


[tool.uv]
required-environments = [
  "sys_platform == 'win32' and platform_machine == 'AMD64'"
]




# Not using now
# python-dotenv>=1.1.0
# qrcode>=8.2

# Not needed for last build
# requests_toolbelt>=1.0.0
# tqdm>=4.67.1
# pyzbar>=0.1.9
# pyzipper>=0.3.6
