from __future__ import annotations
from typing import Protocol, Iterable, Any


class TemplateStorePort(Protocol):
    def list_templates(self) -> list[str]: ...
    def get_template(self, name: str) -> str: ...
    def set_current_template(self, name: str) -> None: ...
    def get_current_template(self) -> str: ...


class DeletedTitlesPort(Protocol):
    def get_deleted_titles(self, batch_size: int = 300, offset: int = 0) -> list[dict]: ...
    def restore_titles(self, ids: list[int]) -> None: ...
    def purge_titles(self, csv_ids: str) -> None: ...


class AuditLogPort(Protocol):
    def get_deleted_titles_log(self, limit: int = 300, offset: int = 0) -> list[dict]: ...
    def get_deleted_titles_log_item(self, log_id: int) -> dict | None: ...


class MaintenancePort(Protocol):
    def optimize_db(self) -> dict: ...
