# player/base_engine.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Callable, Optional, Protocol


@dataclass
class PlaybackState:
    is_playing: bool
    time_ms: int
    length_ms: int
    volume: int
    mrl: str | None = None


class PlayerEngine(Protocol):
    # lifecycle
    def set_video_widget(self, win_id: int) -> None: ...
    def shutdown(self) -> None: ...

    # load
    def load(self, url: str) -> None: ...

    # transport
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def toggle_pause(self) -> bool: ...  # returns new is_playing state
    def stop(self) -> None: ...

    # seek/volume — return True if the operation was accepted, False otherwise
    def seek_ratio(self, ratio: float) -> bool: ...
    def seek_ms(self, ms: int) -> bool: ...
    def set_volume(self, volume: int) -> None: ...

    # info
    def get_state(self) -> PlaybackState: ...
    def is_seekable(self) -> bool: ...
    def get_video_size(self) -> tuple[int, int] | None: ...

    # optional extended capabilities — may not be present on all engines
    def is_buffering_or_seeking(self) -> bool: ...
    def screenshot(self, path: str) -> bool: ...

    # events
    on_eof: Optional[Callable[[], None]]
    on_error: Optional[Callable[[str], None]]
