from __future__ import annotations
from backend.core.ports.notify import NotifierPort


class NullNotifier(NotifierPort):
    def info(self, title: str, message: str) -> None: ...
    def success(self, title: str, message: str) -> None: ...
    def warning(self, title: str, message: str) -> None: ...
    def error(self, title: str, message: str) -> None: ...
