from __future__ import annotations
from typing import Protocol


class NotifierPort(Protocol):
    def info(self, title: str, message: str) -> None: ...
    def success(self, title: str, message: str) -> None: ...
    def warning(self, title: str, message: str) -> None: ...
    def error(self, title: str, message: str) -> None: ...
